# Generated by Django 3.2.3 on 2021-06-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accounts_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='referral_code',
            field=models.IntegerField(),
        ),
    ]
