# Generated by Django 3.2.3 on 2021-06-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_accounts_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='referral_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
