# Generated by Django 3.2.3 on 2021-06-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_accounts_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='parent_id',
            field=models.CharField(default='admin', max_length=250, verbose_name='DS ID'),
        ),
    ]
